#!/bin/bash
#
# create_issue.sh - Create directory structure for a new magazine issue
#
# Usage: ./create_issue.sh <issue_name>
# Example: ./create_issue.sh 4_2025
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if issue name is provided
if [ -z "$1" ]; then
    echo -e "${RED}Error: Issue name required${NC}"
    echo "Usage: $0 <issue_name>"
    echo "Example: $0 4_2025"
    exit 1
fi

ISSUE_NAME="$1"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
ISSUE_DIR="$PROJECT_ROOT/$ISSUE_NAME"

# Check if issue directory already exists
if [ -d "$ISSUE_DIR" ]; then
    echo -e "${YELLOW}Warning: Directory '$ISSUE_NAME' already exists${NC}"
    read -p "Do you want to reinitialize it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
fi

echo -e "${GREEN}Creating magazine issue: $ISSUE_NAME${NC}"
echo "================================================"

# Create directory structure
echo "Creating directories..."
mkdir -p "$ISSUE_DIR"/{source/{articles,images},processed/{articles,images},output}

# Create README for the issue
cat > "$ISSUE_DIR/README.md" << EOF
# Magazine Issue: $ISSUE_NAME

This directory contains all source material and build artifacts for magazine issue $ISSUE_NAME.

## Directory Structure

- **source/** - Original content (DO NOT modify these)
  - **articles/** - DOCX article files from contributors
  - **images/** - Original JPG/TIFF images from contributors

- **processed/** - Generated files (automatically created during build)
  - **articles/** - LaTeX files converted from DOCX
  - **images/** - CMYK PDF images ready for LaTeX inclusion

- **output/** - Final PDFs
  - sissybar_${ISSUE_NAME}.pdf - Final magazine for printing

## Workflow

### 1. Collect Content

Place contributor content in the source directories:
\`\`\`bash
cp path/to/article.docx source/articles/01_kansi.docx
cp path/to/photos/* source/images/
\`\`\`

### 2. Build Magazine

Run the build script from the project root:
\`\`\`bash
cd /Users/superuser/projects/yccf/sissybar
./scripts/build_magazine.sh $ISSUE_NAME
\`\`\`

Or use make:
\`\`\`bash
make issue=$ISSUE_NAME
\`\`\`

### 3. Review Output

The final PDF will be in:
\`\`\`
output/sissybar_${ISSUE_NAME}.pdf
\`\`\`

## Manual Fine-Tuning

If you need to manually adjust layouts:

1. After initial build, edit the LaTeX files in \`processed/articles/\`
2. Rebuild with: \`./scripts/build_magazine.sh $ISSUE_NAME --no-convert\`

## Quick Commands

\`\`\`bash
# Full build (convert + process + compile)
./scripts/build_magazine.sh $ISSUE_NAME

# Build without converting DOCX (use existing .tex files)
./scripts/build_magazine.sh $ISSUE_NAME --no-convert

# Draft build (faster, RGB images, no crop marks)
./scripts/build_magazine.sh $ISSUE_NAME --draft

# Clean build artifacts
./scripts/build_magazine.sh $ISSUE_NAME --clean
\`\`\`

## Created: $(date +"%Y-%m-%d %H:%M")
EOF

# Create issue-specific main LaTeX file (template - will be updated after LaTeX template is ready)
cat > "$ISSUE_DIR/magazine_${ISSUE_NAME}.tex" << EOF
% Magazine Issue: $ISSUE_NAME
% Generated: $(date +"%Y-%m-%d %H:%M")
%
% This is a placeholder file. It will be updated when the LaTeX template is created.
% Do not edit this file manually - it's regenerated during build.

\documentclass[a4paper,showtrims]{memoir}

% TODO: Add proper magazine template configuration

\begin{document}

\title{Sissybar Magazine - Issue $ISSUE_NAME}
\author{YCCF}
\date{$(date +"%B %Y")}
\maketitle

% Articles will be included here automatically during build

\end{document}
EOF

# Create .gitkeep files to preserve empty directories in git
touch "$ISSUE_DIR/source/articles/.gitkeep"
touch "$ISSUE_DIR/source/images/.gitkeep"
touch "$ISSUE_DIR/processed/articles/.gitkeep"
touch "$ISSUE_DIR/processed/images/.gitkeep"
touch "$ISSUE_DIR/output/.gitkeep"

echo ""
echo -e "${GREEN}✓ Issue structure created successfully!${NC}"
echo ""
echo "Directory: $ISSUE_DIR"
echo ""
echo "Next steps:"
echo "1. Place article DOCX files in: $ISSUE_NAME/source/articles/"
echo "2. Place images in: $ISSUE_NAME/source/images/"
echo "3. Run: ./scripts/build_magazine.sh $ISSUE_NAME"
echo ""

# Show directory tree
if command -v tree &> /dev/null; then
    echo "Structure created:"
    tree -L 2 "$ISSUE_DIR"
else
    echo "Structure created:"
    find "$ISSUE_DIR" -type d | sed "s|$ISSUE_DIR|.|" | sort
fi

echo ""
echo -e "${GREEN}Done!${NC}"
